# Unusual Whales Sector ETF Tide Feed Settings
# Configuration for sector ETF analysis and tide data collection

api:
  unusual_whales:
    base_url: "https://api.unusualwhales.com/api"
    timeout: 30
    max_retries: 3
    retry_delay: 5
    rate_limit_delay: 1.0  # Delay between API calls to respect rate limits

collection:
  # Sector ETFs to monitor for tide analysis
  sector_etfs:
    - "XLK"   # Technology
    - "XLF"   # Financial
    - "XLE"   # Energy
    - "XLI"   # Industrial
    - "XLV"   # Healthcare
    - "XLY"   # Consumer Discretionary
    - "XLP"   # Consumer Staples
    - "XLU"   # Utilities
    - "XLB"   # Materials
    - "XLRE"  # Real Estate
    - "XLC"   # Communication

  # Additional market ETFs for comparison
  market_etfs:
    - "SPY"   # S&P 500
    - "QQQ"   # NASDAQ
    - "IWM"   # Russell 2000
    - "VTI"   # Total Stock Market

  # Collection intervals (seconds)
  market_hours_interval: 300      # 5 minutes during market hours
  after_hours_interval: 900       # 15 minutes during after hours
  weekend_interval: 1800          # 30 minutes on weekends

  # Data collection settings
  lookback_days: 5                # Historical data lookback
  include_holdings: true          # Fetch ETF holdings data
  include_exposure: true          # Fetch ETF exposure data
  include_weights: true           # Fetch sector/country weights
  include_inflow_outflow: true    # Fetch inflow/outflow data

processing:
  # Tide analysis thresholds
  tide_thresholds:
    strong_bullish: 100000000     # $100M+ net call premium
    moderate_bullish: 50000000    # $50M+ net call premium
    neutral_low: -25000000        # -$25M to +$25M
    neutral_high: 25000000
    moderate_bearish: -50000000   # -$50M+ net put premium
    strong_bearish: -100000000    # -$100M+ net put premium

  # Volume analysis
  volume_analysis:
    unusual_volume_threshold: 2.0  # 2x average volume
    min_volume_filter: 100000      # Minimum daily volume
    volume_spike_threshold: 3.0    # 3x volume spike detection

  # Holdings analysis
  holdings_analysis:
    min_weight_threshold: 0.01     # 1% minimum weight in ETF
    weight_change_threshold: 0.005 # 0.5% weight change significance
    top_holdings_count: 20         # Track top N holdings

  # Sector rotation detection
  sector_rotation:
    momentum_window: 5             # Days for momentum calculation
    rotation_threshold: 0.02       # 2% relative performance threshold
    correlation_window: 20         # Days for correlation analysis

questdb:
  host: "localhost"
  port: 8812
  database: "qdb"
  user: "admin"
  password: "quest"
  batch_size: 100

# Table schemas for QuestDB
schemas:
  etf_tide_data:
    table_name: "etf_tide_data"
    partition: "DAY"
    timestamp_column: "timestamp"

  etf_holdings_data:
    table_name: "etf_holdings_data"
    partition: "DAY"
    timestamp_column: "timestamp"

  etf_exposure_data:
    table_name: "etf_exposure_data"
    partition: "DAY"
    timestamp_column: "timestamp"

  etf_weights_data:
    table_name: "etf_weights_data"
    partition: "DAY"
    timestamp_column: "timestamp"

  etf_inflow_outflow_data:
    table_name: "etf_inflow_outflow_data"
    partition: "DAY"
    timestamp_column: "timestamp"

# Logging configuration
logging:
  level: "INFO"
  log_file: "/var/log/ezbot/sector_etf_tide_feed.log"
  max_file_size: "10MB"
  backup_count: 5