# VIX Feed Configuration for Volatility Data Collection
# Uses Yahoo Finance for free, reliable VIX data with 15-minute delay
# Supports all VIX variants and related ETFs/ETNs

api:
  # Yahoo Finance settings
  yfinance:
    timeout: 30  # seconds
    max_retries: 3
    retry_delay: 5  # seconds
    auto_adjust: true  # Auto-adjust OHLC for splits/dividends
    prepost: false  # Include pre/post market data

collection:
  # Collection intervals based on market status
  market_hours_interval: 300  # 5 minutes during market hours (9:30-4:00 ET)
  after_hours_interval: 900   # 15 minutes after hours (4:00-9:30 ET)
  weekend_interval: 1800      # 30 minutes on weekends (VIX futures still trade)

  # VIX symbols to track
  vix_indices:
    - "^VIX"    # CBOE Volatility Index (30-day)
    - "^VIX9D"  # CBOE 9-day Volatility Index
    - "^VIX3M"  # CBOE 3-month Volatility Index
    - "^VIX6M"  # CBOE 6-month Volatility Index

  # VIX-related ETFs and ETNs
  vix_products:
    - "UVXY"    # 1.5x VIX Short-Term Futures ETF
    - "SVXY"    # -0.5x VIX Short-Term Futures ETF
    - "VXX"     # VIX Short-Term Futures ETN
    - "VIXY"    # VIX Short-Term Futures ETF
    - "VIXM"    # VIX Mid-Term Futures ETF

  # Data collection parameters
  period: "1d"        # Yahoo Finance period (1d for intraday)
  interval: "5m"      # 5-minute intervals
  max_data_points: 100  # Maximum data points per request

processing:
  # VIX analysis and calculations
  calculate_percentiles: true
  percentile_window: 252  # 252 trading days (1 year)

  # VIX regime classification
  vix_levels:
    low: 15.0      # Below 15 = low volatility regime
    medium: 25.0   # 15-25 = medium volatility
    high: 35.0     # 25-35 = high volatility
    extreme: 50.0  # Above 35+ = extreme volatility/crisis

  # Term structure analysis
  term_structure:
    enabled: true
    contango_threshold: 1.05    # VIX3M/VIX > 1.05 = contango
    backwardation_threshold: 0.95  # VIX3M/VIX < 0.95 = backwardation

  # Fear and greed indicators
  fear_indicators:
    vix9d_vix_ratio: true      # Short vs medium term fear
    vix_products_divergence: true  # ETF premium/discount analysis

questdb:
  # Connection settings
  host: "localhost"
  port: 8812  # PostgreSQL interface port
  database: "qdb"

  # Table configuration
  table_name: "vix_data"

  # Data retention
  retention_days: 365  # Keep VIX data for 1 year

  # Batch processing
  batch_size: 50
  flush_interval: 30  # seconds

# Alert settings for VIX regime changes
alerts:
  enabled: true

  # VIX spike alerts
  vix_spikes:
    enabled: true
    spike_threshold: 5.0  # Alert on 5+ point VIX moves
    time_window: 300     # 5 minutes

  # Regime change alerts
  regime_changes:
    enabled: true
    notify_on_regime_shift: true

  # Term structure alerts
  term_structure_alerts:
    enabled: true
    backwardation_alert: true  # Alert when VIX curve inverts
    extreme_contango_alert: true  # Alert on extreme contango

  # Webhook for alerts (optional)
  webhook_url: ""  # Set if you want Slack/Discord notifications

# VIX-specific queries for analysis
vix_queries:
  # Current VIX regime analysis
  current_regime: |
    SELECT symbol, price,
           CASE
               WHEN price < 15 THEN 'low'
               WHEN price < 25 THEN 'medium'
               WHEN price < 35 THEN 'high'
               ELSE 'extreme'
           END as regime,
           percentile_rank,
           timestamp
    FROM vix_data
    WHERE symbol = '^VIX'
      AND timestamp = (SELECT MAX(timestamp) FROM vix_data WHERE symbol = '^VIX')
    ORDER BY timestamp DESC;

  # VIX term structure
  term_structure: |
    SELECT
        v1.price as vix_current,
        v3.price as vix_3m,
        v6.price as vix_6m,
        (v3.price / v1.price) as term_structure_ratio,
        CASE
            WHEN v3.price / v1.price > 1.05 THEN 'contango'
            WHEN v3.price / v1.price < 0.95 THEN 'backwardation'
            ELSE 'normal'
        END as structure_type,
        v1.timestamp
    FROM vix_data v1
    JOIN vix_data v3 ON v1.timestamp = v3.timestamp AND v3.symbol = '^VIX3M'
    JOIN vix_data v6 ON v1.timestamp = v6.timestamp AND v6.symbol = '^VIX6M'
    WHERE v1.symbol = '^VIX'
      AND v1.timestamp > dateadd('h', -1, now())
    ORDER BY v1.timestamp DESC
    LIMIT 1;

  # VIX products performance
  vix_products_performance: |
    SELECT symbol, price, change_percent,
           timestamp
    FROM vix_data
    WHERE symbol IN ('UVXY', 'SVXY', 'VXX', 'VIXY', 'VIXM')
      AND timestamp > dateadd('h', -1, now())
    ORDER BY symbol, timestamp DESC;

# Cache settings
cache:
  enabled: true
  ttl: 60  # 1 minute cache for API responses
  max_size: 500  # max cached items

logging:
  level: "INFO"
  file: "vix_feed.log"
  max_size_mb: 50
  backup_count: 3
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"