# News Feed Configuration for Financial Data Collection

api:
  # Polygon.io API settings
  polygon:
    base_url: "https://api.polygon.io/v2/reference/news"
    token_env_var: "POLYGON_API_KEY"
    rate_limit: 60  # requests per minute
    timeout: 30  # seconds
    max_retries: 3
    retry_delay: 2  # seconds
    max_limit: 1000  # max articles per request

  # Unusual Whales API settings
  unusual_whales:
    base_url: "https://api.unusualwhales.com/api"
    token: ""  # Add your token here or set UNUSUAL_WHALES_TOKEN env var
    rate_limit: 60  # requests per minute
    timeout: 30  # seconds
    max_retries: 3
    retry_delay: 2  # seconds
    max_limit: 100  # max articles per request

  # Stock Titan RSS settings
  stock_titan:
    rss_url: "https://www.stocktitan.net/rss"
    timeout: 30  # seconds
    max_retries: 3
    retry_delay: 2  # seconds
    max_limit: 50  # max articles per request

collection:
  # How often to poll for new news
  poll_interval: 180  # 3 minutes during market hours
  after_hours_interval: 600  # 10 minutes after hours
  weekend_interval: 1800  # 30 minutes on weekends

  # Data collection parameters
  default_hours_lookback: 24  # Only collect news from last 24 hours
  breaking_news_hours: 2  # Consider news "breaking" if within 2 hours
  max_articles_per_source: 1000  # Maximum articles to fetch per source

  # Active hours (EST)
  market_hours:
    start: "09:00"
    end: "16:30"

  extended_hours:
    start: "04:00"
    end: "20:00"

filters:
  # Content filtering
  min_title_length: 10
  max_title_length: 500
  min_description_length: 0
  max_description_length: 2000

  # Ticker filtering
  valid_ticker_pattern: "^[A-Z]{1,5}$"
  excluded_tickers: ["SPAC", "ETF", "FUND"]

  # Category filtering
  track_categories:
    - "earnings"
    - "acquisitions"
    - "fda"
    - "ipo"
    - "offerings"
    - "dividends"
    - "splits"
    - "leadership"
    - "partnerships"
    - "products"
    - "legal"
    - "analyst"
    - "federal-reserve"
    - "market"
    - "general"

  # Sentiment filtering
  track_sentiments:
    - "positive"
    - "negative"
    - "neutral"

processing:
  # Text processing
  clean_html: true
  extract_tickers: true
  calculate_sentiment: true
  categorize_news: true

  # Impact scoring
  enable_impact_scoring: true
  impact_factors:
    is_major: 0.5
    sentiment_weight: 0.3
    ticker_count_weight: 0.1
    category_weight: 0.4

  # Deduplication
  enable_deduplication: true
  similarity_threshold: 0.85  # Articles with >85% similarity are considered duplicates
  dedup_time_window: 3600  # seconds (1 hour)

questdb:
  # Connection settings
  host: "localhost"
  port: 8812  # PostgreSQL interface port
  database: "qdb"

  # Table names - separate table for each source
  tables:
    polygon_news: "polygon_news"
    unusual_whales_news: "unusual_whales_news"
    stock_titan_news: "stock_titan_news"

  # Data retention
  retention_days: 90  # Keep news for 90 days

  # Batch processing
  batch_size: 100
  flush_interval: 60  # seconds

logging:
  level: "INFO"
  file: "news_feed.log"
  max_size_mb: 100
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Alert settings for significant news
alerts:
  enabled: true

  # Breaking news alerts
  breaking_news:
    enabled: true
    min_impact_score: 0.7
    major_news_only: false

  # Market moving news
  market_impact:
    enabled: true
    categories: ["earnings", "fda", "acquisitions", "federal-reserve"]
    min_sentiment_change: 0.5

  # Ticker-specific alerts
  ticker_alerts:
    enabled: true
    min_articles_threshold: 3  # Alert if ticker gets 3+ articles in short time
    time_window: 1800  # 30 minutes

  # Webhook for alerts (optional)
  webhook_url: ""  # Set if you want Slack/Discord notifications

# Source priorities (1=highest, 10=lowest)
source_priorities:
  polygon_api: 2
  unusual_whales_api: 1
  stock_titan_rss: 3

# Cache settings
cache:
  enabled: true
  ttl: 300  # 5 minutes
  max_size: 10000  # max cached items