# Account Feed Settings Configuration
# Alpaca Paper Trading Account Monitoring

# Collection intervals (in seconds)
collection_intervals:
  market_hours: 60      # Every 1 minute during market hours
  extended_hours: 300   # Every 5 minutes during extended hours
  off_hours: 1800       # Every 30 minutes during off hours

# Order feed specific intervals
order_intervals:
  market_hours: 30      # Every 30 seconds during market hours
  extended_hours: 120   # Every 2 minutes during extended hours
  off_hours: 600        # Every 10 minutes during off hours

# Position feed specific intervals
position_intervals:
  market_hours: 30      # Every 30 seconds during market hours
  extended_hours: 120   # Every 2 minutes during extended hours
  off_hours: 600        # Every 10 minutes during off hours

# Trade updates feed specific intervals
update_intervals:
  market_hours: 30      # Every 30 seconds during market hours
  extended_hours: 120   # Every 2 minutes during extended hours
  off_hours: 600        # Every 10 minutes during off hours

# QuestDB connection settings
questdb:
  host: "localhost"
  port: 8812
  database: "qdb"
  batch_size: 100

# Alpaca API settings
alpaca:
  paper_trading: true
  websocket_retry_attempts: 5
  websocket_retry_delay: 10

# Account monitoring settings
account_monitoring:
  track_buying_power: true
  track_positions: true
  track_day_trades: true
  alert_thresholds:
    low_buying_power: 1000.0
    high_day_trade_count: 2
    portfolio_drop_percent: 5.0

# Order monitoring settings
order_monitoring:
  track_all_statuses: true
  track_filled_orders: true
  track_canceled_orders: true
  max_orders_per_request: 500

# Position monitoring settings
position_monitoring:
  track_unrealized_pl: true
  track_market_value: true
  alert_thresholds:
    position_loss_percent: 10.0
    position_gain_percent: 20.0

# Trade monitoring settings
trade_monitoring:
  track_all_fills: true
  track_large_trades: true
  alert_thresholds:
    large_trade_amount: 10000.0

# WebSocket streaming settings
websocket:
  reconnect_attempts: 5
  reconnect_delay: 10
  heartbeat_interval: 30
  subscription_streams:
    - "trade_updates"

# Data retention settings
data_retention:
  account_data_days: 365
  order_data_days: 365
  position_data_days: 365
  trade_updates_days: 365

# Logging and output settings
output:
  console_logging: true
  verbose_mode: true
  show_timestamps: true
  format_currency: true