# Default Feed Configuration Template
# These settings are inherited by all feeds unless overridden

api:
  timeout: 30
  max_retries: 3
  retry_delay: 5
  rate_limit:
    requests_per_second: 10
    requests_per_minute: 500

collection:
  batch_size: 100
  max_records_per_run: 10000

database:
  batch_size: 1000
  timeout: 30
  retry_attempts: 3

telemetry:
  enabled: true
  store_metrics: true
  track_performance: true
  track_resources: true
  track_data_quality: true

alerts:
  enabled: true
  max_execution_time_ms: 30000
  min_data_quality_score: 85.0
  min_records_per_execution: 1
  max_consecutive_failures: 5

validation:
  enabled: true
  strict_mode: false
  max_null_percentage: 15.0
  required_fields: ["timestamp"]

logging:
  level: "INFO"
  format: "structured"
  include_context: true

health_check:
  max_execution_age_seconds: 3600
  min_success_rate: 90.0